### PR TITLE
coredns: remove force_tcp option in nodelocaldns configmap

### PR DESCRIPTION
**Pull request by thomasferrandiz**
Ref: SURE-9325

### CODE REVIEW

**Review by rbrtbnfgl — APPROVED** [review]

**Comment by manuelbuil** [comment]
Are there any potential bad consequences of removing that option?

**Comment by thomasferrandiz** [comment]
> Are there any potential bad consequences of removing that option?

I don't think so, they remove it in the upstream manifest years ago and it's still the default.
The only thing I can think of is where a user has TCP port 53 open but not UDP:53.
But they can still adapt the configuration anyway.

**Review by manuelbuil — APPROVED** [review]

**Comment by manuelbuil** [comment]
BTW, line 63 has another `force_tcp` line, should that also be removed?

**Comment by thomasferrandiz** [comment]
> BTW, line 63 has another `force_tcp` line, should that also be removed?

I don't think so, the other `force_tcp` are still in the upstream manifest.

**Pull request merged**
