### PR TITLE
Updated calico chart to expose felix cfg props exposed in canal

### PR DESCRIPTION
**Pull request by ron1**
Updated calico chart to expose felix config properties exposed in canal chart. See issue https://github.com/rancher/rke2/issues/3091

### CODE REVIEW

**Review by dereknola — APPROVED** [review]
LGTM

**Review by dereknola — CHANGES_REQUESTED** [review]
You need to bump the chart version https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-calico/package.yaml#L2

**Review by brandond — APPROVED** [review]

**Comment by ron1** [comment]
@dereknola do you have a moment to give this PR a final review?

**Review by dereknola — APPROVED** [review]

**Comment by manuelbuil** [comment]
We had to remove the fields:
```
iptablesRefreshInterval:
iptablesBackend:
```
from the felix configuration in the latest release because in Calico v3.24.1, calico-node was failing due to these parameters. I suspect there is a bug in how the calico operator is passing these values because calico-node was not recognizing a valid string for iptablesBackend or a valid integer for iptablesRefreshInterval. As passing values like this is not the recommended way by Calico, they are probably never testing it

**Pull request merged**
