### PR TITLE
Start consuming upstream rke2-multus chart

### PR DESCRIPTION
**Pull request by manuelbuil**
Signed-off-by: Manuel Buil <mbuil@suse.com>

### CODE REVIEW

**Review by brandond — APPROVED** [review]
Big change! Does this upgrade cleanly on existing installs?

**Comment by manuelbuil** [comment]
> Big change! Does this upgrade cleanly on existing installs?

Good point, I will test it next week. To be fair, the real changes are quite small, almost none. I made this to basically simplify our maintenance

**Comment by manuelbuil** [comment]
The big change comes in another PR that I will create next week if I have time ;)

**Comment by manuelbuil** [comment]
I just had some time. `helm upgrade` works perfectly!

**Review by rbrtbnfgl — APPROVED** [review]

**Pull request merged**
