### PR TITLE
Add harvester-cloud-provider and harvester-csi-driver

### PR DESCRIPTION
**Pull request by yaocw2020**
issue: https://github.com/rancher/rke2/issues/1680

### CODE REVIEW

**Review by dweomer — CHANGES_REQUESTED** [review]
Please see https://github.com/rancher/rke2-charts#basic-commands for instructions on the steps to perform to submit a PR. Specifically, it looks as if `make clean` was not run as there are `assets/*` and `charts/*` and `index.yaml` in this PR. The automation takes care of this for us, please do not include it in your PR.

**Comment by yaocw2020** [comment]
> Please see https://github.com/rancher/rke2-charts#basic-commands for instructions on the steps to perform to submit a PR. Specifically, it looks as if `make clean` was not run as there are `assets/*` and `charts/*` and `index.yaml` in this PR. The automation takes care of this for us, please do not include it in your PR.

Oh, it is so convenient. And what's the version form generated by automation?

**Review by dweomer — APPROVED** [review]

**Comment by brandond** [comment]
We inject a number of cluster configuration values into charts; the most important of which is the systemDefaultRegistry. If set this should be used as a registry prefix for all the images used by the chart.

The list of variables is listed here:
* https://github.com/rancher/rke2/blob/82ca956e2d43e7e10223375c7e9614ac3acf6d0c/pkg/bootstrap/bootstrap.go#L268-L274

For an example of other charts using this you can look at
* https://github.com/rancher/rke2-charts/blob/de5dd4c9f4ded7c08b4417922f691139d2417e9f/packages/rke2-canal/charts/templates/_helpers.tpl#L1-L7
* https://github.com/rancher/rke2-charts/blob/de5dd4c9f4ded7c08b4417922f691139d2417e9f/packages/rke2-canal/charts/templates/daemonset.yaml#L53

**Review by brandond — CHANGES_REQUESTED** [review]
needs system-default-registry support as describe above.

**Comment by yaocw2020** [comment]
> needs system-default-registry support as describe above.

Done! @brandond

**Comment by guangbochen** [comment]
the chart is updated and it was addressed via https://github.com/harvester/charts/pull/22, thanks.

**Review by brandond — APPROVED** [review]
lgtm!

**Pull request merged**
